### ISSUE TITLE
New Business Request

### ISSUE THREAD

**Issue by kratsg** [kratsg/deaf-owned-businesses#10]
```
- category: 
  comments: null
  location: https://www.etsy.com/shop/WildBluebonnetShop
  name: Wild Bluebonnet Shop 
  url: https://www.etsy.com/shop/WildBluebonnetShop
```

Submitted by [Alicia Wooten](mailto:aliciakozue@gmail.com) at 11/30/2018 11:44:25 from [DeafBiz Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdFPZyanfu-_nkWpKKwIIk15NzeoBXgkg5xSp4c5CrBlSoARw/viewform) automatically.
