### ISSUE TITLE
New Business Request

### ISSUE THREAD

**Issue by kratsg** [kratsg/deaf-owned-businesses#11]
```
- category: 
  comments: null
  location: null
  name: 
  url: 
```

Submitted by [](mailto:) at 11/30/2018 11:45:04 from [DeafBiz Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdFPZyanfu-_nkWpKKwIIk15NzeoBXgkg5xSp4c5CrBlSoARw/viewform) automatically.
