### ISSUE TITLE
New Business Request

### ISSUE THREAD

**Issue by kratsg** [kratsg/deaf-owned-businesses#8]
```
  category: 
  comments: null
- location: null
  name: https://abc.xyz
  url: 
```

Submitted by [ABC LLC](mailto:test@me.com) at 11/30/2018 10:43:00 from [DeafBiz Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdFPZyanfu-_nkWpKKwIIk15NzeoBXgkg5xSp4c5CrBlSoARw/viewform) automatically.
